name: CC 

on: [push]

env:
  CARGO_TERM_COLOR: always
 
jobs:
  # based on example https://github.com/taiki-e/cargo-llvm-cov?tab=readme-ov-file#continuous-integration
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rustup update
        run: rustup update stable
      - name: Install cargo-llvm-co
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        run: cargo llvm-cov --tests --lcov --output-path lcov.info
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          slug: solc42/fibi-proxy          
          fail_ci_if_error: true
